# Generated by Django 5.1.4 on 2024-12-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_sold',
            name='price_sale_car',
            field=models.IntegerField(),
        ),
    ]
