# Generated by Django 5.1.4 on 2024-12-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_repairs_type_car_request_repairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_sold',
            name='manufacture_date_car',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='request_sold',
            name='statues',
            field=models.CharField(choices=[('Confirm', 'Confirm'), ('Refuse', 'Refuse')], default='Wating', max_length=50),
        ),
    ]
