# Generated by Django 5.1.4 on 2024-12-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_request_sold_manufacture_date_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='statues',
            field=models.CharField(choices=[('Confirm', 'Confirm'), ('Refuse', 'Refuse')], default='Wating', max_length=50),
        ),
    ]
