# Generated by Django 5.1.4 on 2024-12-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_cars_status_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
