# Generated by Django 5.1.4 on 2024-12-24 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_reservation_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.cars'),
        ),
    ]
