# Generated by Django 5.1.4 on 2024-12-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_reservation_id_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_sold',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
