# Generated by Django 5.1.4 on 2024-12-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_alter_reservation_id_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='id_car',
        ),
        migrations.AddField(
            model_name='reservation',
            name='id_car',
            field=models.ManyToManyField(to='customer.cars'),
        ),
    ]
