# Generated by Django 5.1.4 on 2024-12-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_remove_reservation_id_car_reservation_id_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_sold',
            name='manufacture_date_car',
            field=models.DateField(),
        ),
    ]
