# Generated by Django 5.1.4 on 2024-12-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_request_repairs_statues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
