# Generated by Django 5.1.4 on 2024-12-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_alter_drivers_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='mangers',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
